dotenv: [".env"]

includes:
  hardware:
    aliases: [hw]
    taskfile: ./system/hardware.yml
  os: ./system/os.yml
  packages:
    aliases: [pkg]
    taskfile: ./system/packages.yml
  # setup: ./setup/setup.yml
  setup:
    aliases: [set]
    taskfile: ./setup/

tasks:
  default:
    cmds:
      - echo Current Taskfile = $(pwd)
      - task -a
    desc: Show current Taskfile location and available commands.
    silent: true
  update:
    aliases: [up]
    cmds:
      - task: setup:update-actl
    desc: Update actl tool.

version: 3
