dotenv: [".env"]

includes:
  hardware:
    aliases: [hw]
    taskfile: ./system/hardware.yml
  os: ./system/os.yml
  packages:
    aliases: [pkg]
    taskfile: ./system/packages.yml
  setup:
    aliases: [set]
    taskfile: ./setup/
  utils: ./core/utils.yml

tasks:
  default:
    cmds:
      - echo Current Taskfile = $(pwd)
      - task -a
    desc: Show current Taskfile location and available commands.
    silent: true
  git-config-*:
    cmds:
      - task: utils:git-config
        vars:
          GIT_ACCOUNT_TYPE: "{{index .MATCH 0}}"
    desc: Configure git username and email.
  update:
    aliases: [up]
    cmds:
      - task: setup:ini:update-actl
    desc: Update actl tool.

version: 3
