version: 3

dotenv: [".env"]

includes:
  vars:
    flatten: true
    taskfile: ./core/vars.yml
  utils: ./core/utils.yml
  tasks:
    flatten: true
    taskfile: ./core/tasks.yml
  dotfiles:
    aliases: [df]
    taskfile: ./setup/dotfiles.yml
  hardware:
    aliases: [hw]
    taskfile: ./system/hardware.yml
  ini: ./setup/init.yml
  os: ./system/os.yml
  packages:
    aliases: [pkg]
    taskfile: ./system/packages.yml
