# Initialization task for a new setup
includes:
  dotfiles:
    aliases: [df]
    taskfile: ./dotfiles.yml
  ini: ./init.yml

vars:
  CODE_FOLDERS:
    - personal
    - others
    - company
  PERSONAL_CODE_DIR: "{{ .WORKSPACE_PATH }}/code/personal"
  PERSONAL_REPO_URL: https://github.com/agonza05
  PERSONAL_REPOS:
    - actl
    - dotfiles
  WORKSPACE_FOLDERS:
    - package
    - config
    - env
    - venv
    - vsc
    - secret
  WORKSPACE_PATH: ${HOME}/tasktest/workspace

version: 3
